# Generated by Django 3.1.6 on 2021-12-06 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='box',
            name='volume',
        ),
    ]
