# Generated by Django 3.1.6 on 2021-12-06 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_box_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='volume',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
