# Generated by Django 3.1.6 on 2021-12-06 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_box_volume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='box',
            name='volume',
        ),
    ]
