# Generated by Django 3.1.6 on 2021-12-06 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_box_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
