# Generated by Django 3.1.6 on 2021-12-07 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0008_box_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='box',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='box',
            name='user',
        ),
        migrations.AlterField(
            model_name='box',
            name='updator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
