# Generated by Django 3.1.6 on 2021-12-07 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20211207_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='volume',
            field=models.IntegerField(default=0),
        ),
    ]
