# Generated by Django 3.1.6 on 2021-12-08 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_box_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='area',
            field=models.IntegerField(default=0),
        ),
    ]
