# Generated by Django 3.1.6 on 2021-12-09 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_box_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='created_on',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='box',
            name='last_modified_on',
            field=models.DateField(auto_now=True),
        ),
    ]
